# Generated by Django 6.0.5 on 2026-06-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_systemsettings_clientprofile_emails_sent_today_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Privacy Policy", max_length=200)),
                (
                    "slug",
                    models.SlugField(help_text="e.g., privacy-policy", unique=True),
                ),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Setup Tier", max_length=100)),
                ("price", models.CharField(default="₹35,000", max_length=50)),
                (
                    "features",
                    models.TextField(
                        help_text="List features separated by commas (e.g., AI Routing, API setup, Support)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="AutoEmail SaaS", max_length=100),
                ),
                (
                    "hero_title",
                    models.CharField(default="Next-Gen AI Automation", max_length=200),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Save hours of manual work with intelligent routing."
                    ),
                ),
                (
                    "space_background_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional link to a custom space background image.",
                    ),
                ),
            ],
        ),
    ]
