# Generated by Django 6.0.5 on 2026-06-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_policy_pricingplan_sitesetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="campaign_images/"
            ),
        ),
    ]
