# Generated by Django 6.0.5 on 2026-06-13 01:43

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_emailtemplate_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientprofile",
            options={
                "verbose_name": "Client Profile",
                "verbose_name_plural": "Client Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="emaillog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
            },
        ),
        migrations.AlterModelOptions(
            name="policy",
            options={"verbose_name_plural": "Policies"},
        ),
        migrations.AlterModelOptions(
            name="pricingplan",
            options={"ordering": ["price"]},
        ),
        migrations.AlterModelOptions(
            name="systemsettings",
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.RemoveField(
            model_name="emaillog",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=datetime.datetime(
                    2026, 6, 13, 1, 41, 54, 704154, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="correlation_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=datetime.datetime(
                    2026, 6, 13, 1, 43, 15, 835993, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emaillog",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.emailtemplate",
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=datetime.datetime(
                    2026, 6, 13, 1, 43, 24, 312541, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Set to False instead of deleting to preserve log integrity.",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="policy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=datetime.datetime(
                    2026, 6, 13, 1, 43, 30, 639001, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="policy",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=datetime.datetime(
                    2026, 6, 13, 1, 43, 38, 355822, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=datetime.datetime(
                    2026, 6, 13, 1, 43, 41, 809263, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="google_sheet_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="invite_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="is_engine_active",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="user",
            field=models.OneToOneField(
                default=datetime.datetime(
                    2026, 6, 13, 1, 43, 51, 666035, tzinfo=datetime.timezone.utc
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="recipient_email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("PROCESSING", "Processing"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("BOUNCED", "Bounced"),
                ],
                db_index=True,
                default="QUEUED",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="project_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="space_background_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="is_engine_paused",
            field=models.BooleanField(
                default=False,
                help_text="Instantly stop all background emails globally.",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailtemplate",
            unique_together={("client", "project_id")},
        ),
        migrations.AddIndex(
            model_name="clientprofile",
            index=models.Index(
                fields=["is_engine_active", "last_scanned"],
                name="core_client_is_engi_b2f1e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["client", "status", "-created_at"],
                name="core_emaill_client__ed47c9_idx",
            ),
        ),
    ]
